#! /usr/bin/env python3
#
# This application can provide quick answers to
# what a program does. A bit like the wtf-applications

import socket
import re
from argparse import ArgumentParser

def main(args):
    data = "GET /explain?cmd=" + args + " HTTP/1.0\r\n\r\n"
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(("explainshell.com", 80))
    s.sendall(data.encode())
    data = b""
    while 1:
        tmp = s.recv(1024)
        if not tmp: break
        data += tmp
    rematch = re.search("<pre class=\"help-box\".*?>(.*?)</pre>", data.decode())
    print(rematch.group(1) if rematch else "No explanation found")

if __name__ == "__main__":
    parser = ArgumentParser(description="Explain Shell")
    parser.add_argument("cmd")
    args = parser.parse_args()
    main(args.cmd)
